import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    home: "Home",
    about: "About",
    products: "Products",
    contact: "Contact",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    dashboard: "Dashboard",
    welcome: "Welcome to FarmConnect",
    farmConnectSlogan: "Connecting Farmers Directly with Buyers",
    farmConnectDescription: "Discover fresh, quality produce directly from local farmers. Support sustainable agriculture and get the best prices.",
    browseProducts: "Browse Products",
    learnMore: "Learn More",
    freshProduce: "Fresh Produce",
    freshProduceDesc: "Get the freshest fruits and vegetables directly from farms",
    directFromFarmers: "Direct from Farmers",
    directFromFarmersDesc: "Cut out the middleman and support local agriculture",
    qualityGuaranteed: "Quality Guaranteed",
    qualityGuaranteedDesc: "All products are quality-checked before delivery",
    aboutUs: "About Us",
    ourMission: "Our Mission",
    ourMissionDesc: "FarmConnect bridges the gap between farmers and consumers, ensuring fair prices for farmers and fresh produce for buyers.",
    farmerTestimonial: "FarmConnect has revolutionized how I sell my produce. I now get better prices and direct feedback from customers.",
    buyerTestimonial: "I love getting fresh vegetables directly from farmers. The quality is amazing and the prices are fair.",
    getStarted: "Get Started",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot Password?",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    name: "Name",
    confirmPassword: "Confirm Password",
    phone: "Phone",
    location: "Location",
    adminDashboard: "Admin Dashboard",
    farmerDashboard: "Farmer Dashboard",
    buyerDashboard: "Buyer Dashboard",
    userManagement: "User Management",
    cropManagement: "Crop Management", 
    orderManagement: "Order Management",
    systemAnalytics: "System Analytics",
    salesAnalytics: "Sales Analytics",
    orderTracking: "Order Tracking",
    profileManagement: "Profile Management",
    purchaseAnalytics: "Purchase Analytics",
    orderHistory: "Order History",
    totalUsers: "Total Users",
    totalCrops: "Total Crops",
    totalOrders: "Total Orders",
    pendingOrders: "Pending Orders",
    addCrop: "Add Crop",
    cropName: "Crop Name",
    category: "Category",
    price: "Price",
    quantity: "Quantity",
    farmer: "Farmer",
    buyer: "Buyer",
    amount: "Amount",
    orderDate: "Order Date",
    active: "Active",
    closed: "Closed",
    pending: "Pending",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    closeCrop: "Close Crop",
    markAsShipped: "Mark as Shipped",
    cancelOrder: "Cancel Order",
    update: "Update",
    currency: "EGP",
    subscription: "Subscription",
    subscribed: "Subscribed",
    notSubscribed: "Not Subscribed",
    premiumPlan: "Premium Plan",
    unlimited: "Unlimited",
    support: "Support",
    monthlyPlan: "month",
    subscribe: "Subscribe",
    manageSubscription: "Manage Subscription",
    
    // New wallet translations
    wallet: "Wallet",
    walletBalance: "Wallet Balance",
    availableBalance: "Available Balance",
    recentTransactions: "Recent Transactions",
    walletTransactionHistory: "Your wallet transaction history",
    type: "Type",
    description: "Description",
    date: "Date",
    status: "Status",
    credit: "Credit",
    debit: "Debit",
    completed: "Completed",
    topUpWallet: "Top Up Wallet",
  },
  ar: {
    home: "الرئيسية",
    about: "حول",
    products: "المنتجات",
    contact: "اتصل بنا",
    login: "تسجيل الدخول",
    signup: "إنشاء حساب",
    logout: "تسجيل الخروج",
    dashboard: "لوحة التحكم",
    welcome: "مرحباً بك في FarmConnect",
    farmConnectSlogan: "ربط المزارعين مباشرة بالمشترين",
    farmConnectDescription: "اكتشف المنتجات الطازجة والجودة مباشرة من المزارعين المحليين. ادعم الزراعة المستدامة واحصل على أفضل الأسعار.",
    browseProducts: "تصفح المنتجات",
    learnMore: "تعلم المزيد",
    freshProduce: "منتجات طازجة",
    freshProduceDesc: "احصل على أطازج الفواكه والخضروات مباشرة من المزارع",
    directFromFarmers: "مباشرة من المزارعين",
    directFromFarmersDesc: "تخلص من الوسطاء وادعم الزراعة المحلية",
    qualityGuaranteed: "جودة مضمونة",
    qualityGuaranteedDesc: "جميع المنتجات يتم فحص جودتها قبل التسليم",
    aboutUs: "من نحن",
    ourMission: "مهمتنا",
    ourMissionDesc: "FarmConnect يربط بين المزارعين والمستهلكين، مما يضمن أسعار عادلة للمزارعين ومنتجات طازجة للمشترين.",
    farmerTestimonial: "FarmConnect غيّر الطريقة التي أبيع بها منتجاتي. أحصل الآن على أسعار أفضل وتعليقات مباشرة من العملاء.",
    buyerTestimonial: "أحب الحصول على الخضروات الطازجة مباشرة من المزارعين. الجودة مذهلة والأسعار عادلة.",
    getStarted: "ابدأ الآن",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    dontHaveAccount: "ليس لديك حساب؟",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    name: "الاسم",
    confirmPassword: "تأكيد كلمة المرور",
    phone: "الهاتف",
    location: "الموقع",
    adminDashboard: "لوحة المدير",
    farmerDashboard: "لوحة المزارع",
    buyerDashboard: "لوحة المشتري",
    userManagement: "إدارة المستخدمين",
    cropManagement: "إدارة المحاصيل",
    orderManagement: "إدارة الطلبات",
    systemAnalytics: "تحليلات النظام",
    salesAnalytics: "تحليلات المبيعات",
    orderTracking: "تتبع الطلبات",
    profileManagement: "إدارة الملف الشخصي",
    purchaseAnalytics: "تحليلات الشراء",
    orderHistory: "تاريخ الطلبات",
    totalUsers: "إجمالي المستخدمين",
    totalCrops: "إجمالي المحاصيل",
    totalOrders: "إجمالي الطلبات",
    pendingOrders: "الطلبات المعلقة",
    addCrop: "إضافة محصول",
    cropName: "اسم المحصول",
    category: "الفئة",
    price: "السعر",
    quantity: "الكمية",
    farmer: "المزارع",
    buyer: "المشتري",
    amount: "المبلغ",
    orderDate: "تاريخ الطلب",
    active: "نشط",
    closed: "مغلق",
    pending: "معلق",
    shipped: "تم الشحن",
    delivered: "تم التسليم",
    cancelled: "ملغي",
    closeCrop: "إغلاق المحصول",
    markAsShipped: "تحديد كمشحون",
    cancelOrder: "إلغاء الطلب",
    update: "تحديث",
    currency: "جنيه",
    subscription: "الاشتراك",
    subscribed: "مشترك",
    notSubscribed: "غير مشترك",
    premiumPlan: "الخطة المميزة",
    unlimited: "غير محدود",
    support: "الدعم",
    monthlyPlan: "شهر",
    subscribe: "اشتراك",
    manageSubscription: "إدارة الاشتراك",
    
    // New wallet translations
    wallet: "المحفظة",
    walletBalance: "رصيد المحفظة",
    availableBalance: "الرصيد المتاح",
    recentTransactions: "المعاملات الأخيرة",
    walletTransactionHistory: "تاريخ معاملات محفظتك",
    type: "النوع",
    description: "الوصف",
    date: "التاريخ",
    status: "الحالة",
    credit: "إيداع",
    debit: "سحب",
    completed: "مكتمل",
    topUpWallet: "شحن المحفظة",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key: string): string => {
    return translations[language as keyof typeof translations][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
